config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :questions

  root to: "students#index"

  get '/login' => 'students#login'

  post '/login' => 'students#login'

  get '/logout' => 'students#logout'

  get 'signup' => 'students#new'
  get 'score' => 'students#score'
  post 'test' => 'students#test'
  post 'submittest' => 'students#submittest'

  get 'admin' => 'students#admin'
  post 'addquestion' => 'students#addquestion'

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :scores
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :test
  belongs_to :question
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :tests
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :scores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authorize
  $DIF = {1=>"Easy", 2=>"Medium",3=>"Hard"}
  def authorize
    if params["action"] == "admin"
      cookies.delete(:email)
    else
      email = cookies[:email]
      if !email.present? and params["action"] != "new" and params["action"] != "create"
        redirect_to "/login" and return if params["action"] != "login" 
      elsif params["action"] == "login"
        page = "/students"
        redirect_to page and return
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :option1, :option2, :option3, :option4, :answer, :difficulty)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :set_student_only

  def login
    if params["email"].present? and params["password"].present?
      user = Student.find_by(email: params["email"], password: params["password"])
      if user.present?
        cookies["email"] = user.email
        page = "/students"
        redirect_to page and return
      end
      @invalid = true
    end
    render layout: "login"
  end

  def logout
    cookies.delete(:email)
    cookies.delete(:is_admin)
    redirect_to "/" and return
  end
  def addquestion
    q = Question.new({:title=>params["title"],:option1=>params["option1"],:option2=>params["option2"],:option3=>params["option3"],:option4=>params["option4"],:answer=>params["answer"],:difficulty => params["difficulty"]})
    q.save!
    redirect_to "/admin"
  end

  def submittest
    que = question_params
    total = 0;
    score = 0;
    t = Test.create({:student_id => @student.id})
    que.each do|k,v|
      s =  Score.create({:question_id => k, :test_id => t.id, :answer => v})
      total +=1
      score +=1 if s.question.answer == s.answer
    end
    t.update_columns({:score => score,:total =>total})
    redirect_to "/students", :notice => "You have got #{score} out of #{total}"
  end

  def score
    @student = Student.where(:email => cookies[:email]).last
    render layout: false
  end

  def test
    difficulty = params["difficulty"]
    @question = Question.where(:difficulty => difficulty).order("RAND()").limit(10)
  end

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    render layout: false
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    render layout: "login"
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email, :password)
    end

    def set_student_only
      @student = Student.find_by(email: cookies["email"])
    end

    def question_params
      params.require(:question)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Test App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li class="<%= controller.class == StudentsController and (controller.action_name == 'index' || controller.action_name == 'test')? 'active' : '' %>"><a href="/students">Home</a></li>
        <li class="<%= controller.class == StudentsController and controller.action_name == 'score' ? 'active' : '' %>"><a href="/score">Score</a></li>
        <li><a href="/logout">LOGOUT</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<%= yield %>
  
</div>
</div>
</div>

</body>
</html>

app/views/layouts/login.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Test App</a>

    </div>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :option1 %><br>
    <%= f.text_field :option1 %>
  </div>
  <div class="field">
    <%= f.label :option2 %><br>
    <%= f.text_field :option2 %>
  </div>
  <div class="field">
    <%= f.label :option3 %><br>
    <%= f.text_field :option3 %>
  </div>
  <div class="field">
    <%= f.label :option4 %><br>
    <%= f.text_field :option4 %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.number_field :answer %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.number_field :difficulty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Option1</th>
      <th>Option2</th>
      <th>Option3</th>
      <th>Option4</th>
      <th>Answer</th>
      <th>Difficulty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.option1 %></td>
        <td><%= question.option2 %></td>
        <td><%= question.option3 %></td>
        <td><%= question.option4 %></td>
        <td><%= question.answer %></td>
        <td><%= question.difficulty %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Option1:</strong>
  <%= @question.option1 %>
</p>

<p>
  <strong>Option2:</strong>
  <%= @question.option2 %>
</p>

<p>
  <strong>Option3:</strong>
  <%= @question.option3 %>
</p>

<p>
  <strong>Option4:</strong>
  <%= @question.option4 %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @question.difficulty %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/students/_form.html.erb
<%= form_for @student, :html => { :class => "form-horizontal student" } do |f| %>

  <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                students_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/students/admin.erb
<div class="panel panel-default">
  <div class="panel-body">
<form action="/addquestion" method="post">
<div class="row">
<div class="col-md-10">
Question:
<input type="text" class="form-control" name="title">
<br>
</div>
<div class="col-md-6">
   <label class="radio-inline">1) <input type="text" class="form-control" name="option1">
</div>
<div class="col-md-6">
   <label class="radio-inline">2) <input type="text" class="form-control" name="option2">
</div>
<div class="col-md-6">
   <label class="radio-inline">3) <input type="text" class="form-control" name="option3">
</div>
<div class="col-md-6">
   <label class="radio-inline">4) <input type="text" class="form-control" name="option4">
<br>
</div>

<br>
<div class="col-md-5">
Difficulty:
   <select class="form-control" name="difficulty">
     <option value="1">Easy</option>
     <option value="2">Medium</option>
     <option value="3">Hard</option>
   </select>
</div>
<div class="col-md-5">
   Answer: <input type="integer" class="form-control" name="answer">
</div>


  
</div>
<br>
  <button type="submit" class="btn btn-success">Add Question</button>
<br>
</form>
  </div>
  </div>
<% Question.all.order("id desc").each do |q| %>
<div class="panel panel-default">
  <div class="panel-body">
<div class="row">
<div class="col-md-12">

<h4><%= q.title %></h4>
</div>

<input type="hidden" name="question[<%= q.id %>]" value="5" />
<div class="col-md-6">
   <label class="radio-inline"><input type="radio" name="question[<%= q.id %>]" value="1" disabled>1) <%= q.option1 %></label>
</div>
<div class="col-md-6">
   <label class="radio-inline"><input type="radio" name="question[<%= q.id %>]" value="2" disabled>2) <%= q.option2 %></label>
</div>
<div class="col-md-6">
   <label class="radio-inline"><input type="radio" name="question[<%= q.id %>]" value="3" disabled>3) <%= q.option3 %></label>
<br>

</div>
<div class="col-md-6">

   <label class="radio-inline"><input type="radio" name="question[<%= q.id %>]" value="4" disabled>4) <%= q.option4 %></label>
<br>
</div>
<br>

<div class="col-md-3">
<br>

   <label class="radio-inline">Difficulty: <%= $DIF[q.difficulty.to_i] %>
</div>
<div class="col-md-3">
<br>

   <label class="radio-inline">Answer: <%= q.answer %>
</div>
  
</div>
</div>
</div>
<br>
<% end %>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%= 
 notice.present? ? (`python lib/home.py display:box '#{notice}'`).html_safe : (`python lib/home.py display:none false`).html_safe %>

app/views/students/login.erb
<div class="container">

        <p><br/></p>
        <div class="row">
    
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="page-header text-center">
                        <h3>Student Login</h3>
                    </div>
                        <div class="alert alert-danger alert-dismissible fade in notice-alert" style="<%= 'display:none' unless @invalid.present? %>"role="alert"> Invalid Email/password<button type="button" class="close" onclick="$(this).closest('.alert').hide()"><span aria-hidden="true">×</span></button> 
                          <span id="alert-message">
                          </span>
                        </div>

                        <div class="alert alert-success alert-dismissible fade in notice-alert" style="<%= 'display:none' unless notice.present? %> "role="alert"><button type="button" class="close" onclick="$(this).closest('.alert').hide()"><span aria-hidden="true">×</span></button> 
                          <span id="alert-message">
                            <%= notice %>
                          </span>
                        </div>
                        <form role="form" action="./login" method="post">
                            <div class="form-group">
                                    <label for="exampleInputEmail1">EMAIL</label>
                                    <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                                    <input type="text" class="form-control LoNotSensitive" name="email" required placeholder="Enter email">
                                </div>
                            </div>
                            <input type="hidden" name="redirect_to" value="<%= @redirect_to %>"></input>
                            <div class="form-group">
                                    <label for="exampleInputPassword1">PASSWORD</label>
                                    <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-star"></span></span>
                                    <input type="password" class="form-control" name="password" required placeholder="Password">
                                </div>
                            </div>
                            <hr/>
                            <button id="loginButton" type="submit" class="btn btn-primary "><span class="glyphicon glyphicon-lock"></span> Login</button>
                            <a href="/signup"><button id="loginButton" type="button"  class="btn btn-primary "><span class="glyphicon glyphicon-lock"></span> Signup</button></a>
                            <p><br/></p>
                        </form>
                        <div class="modal fade bs-example-modal-sm" id="myPleaseWait" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">
                                            <span class="glyphicon glyphicon-time">
                                            </span>Please Wait
                                        </h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-info
                                            progress-bar-striped active" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="page-header">
        <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
      </div>
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>

app/views/students/score.erb
<%= 
(`php lib/score.php #{@student.id} #{@student.name} #{@student.email}`).html_safe %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @student.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @student.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @student.password %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/students/test.erb
<h4> Test </h4>
<form action="/submittest" method="post">
  
<% @question.each do |q| %>
<div class="container">

<div class="row">
<div class="col-md-12">

<h4><%= q.title %></h4>
</div>

  <input type="hidden" name="question[<%= q.id %>]" value="5" />
<div class="col-md-6">
   <label class="radio-inline"><input type="radio" name="question[<%= q.id %>]" value="1" ><%= q.option1 %></label>
</div>
<div class="col-md-6">
   <label class="radio-inline"><input type="radio" name="question[<%= q.id %>]" value="2" ><%= q.option2 %></label>
</div>
<div class="col-md-6">
   <label class="radio-inline"><input type="radio" name="question[<%= q.id %>]" value="3" ><%= q.option3 %></label>
</div>
<div class="col-md-6">
   <label class="radio-inline"><input type="radio" name="question[<%= q.id %>]" value="4" ><%= q.option4 %></label>
</div>
  
</div>
</div>
<br>
<% end %>
  <button type="submit" class="btn btn-success">Submit</button>

</form>